### ISSUE TITLE
Get os error 13 in version 5.0.4

### ISSUE THREAD

**Issue by koitococo** [tun2proxy/tproxy-config#10]
### Description:

In commit 56d2631, `get_state_file_path()` in `lib.rs` changed its behavior. On Linux, it returns a path `/var/run/tproxy_config_restore_state.json`, while `/var/run` points to `/run`, which only can be written by root. It causes tun2proxy failed to setup. I'm not sure if the change is purposed. 

I tested on Fedora 40 and Ubuntu 24.04, and all of them get the permission error.

**Comment by blechschmidt** [comment]
The change was desired for security reasons. Everyone can write to `/tmp/` and blindly passing contents of the state file to commands like `ip` is just provoking a privilege escalation.

I am in favor of getting rid of this file entirely.

@ssrlive, do we still need that file? IMO, we do not need it on Linux.

**Comment by koitococo** [comment]
Thanks for your reply. If the state file should not be written by others, `$XDG_RUNTIME_DIR` may be a solution, which is drwx------

**Comment by ssrlive** [comment]
But the code of this crate must run with root privileges.

**Comment by koitococo** [comment]
I use this crate with tun2proxy, with `--unshare` option, and now this function is totally broken. I don't think the code should run with privieges

**Comment by ssrlive** [comment]
The original intention of the design of this temporary file is to ensure that when the program crashes unexpectedly,
we can restore the system to the initial state before running tun2proxy based on the saved intermediate state variables.

**Comment by ssrlive** [comment]
I haven't yet figured out the serious consequences of tampering with this temporary file.

**Comment by ssrlive** [comment]
So I haven't made up my mind whether to remove this temporary file.

**Comment by blechschmidt** [comment]
> I haven't yet figured out the serious consequences of tampering with this temporary file.

https://github.com/tun2proxy/tproxy-config/blob/c62e61a3bd33e6b68482c7b8b0af477e0ca8cd3c/src/linux.rs#L488

`restore_socket_fwmark` is part of `TProxyState`. Now if `restore_socket_fwmark` is `netns exec test /bin/sh`, we have a privilege escalation.

**Comment by blechschmidt** [comment]
In tun2proxy, we currently don't even use that file. The cleanup is done through the OS-specific implementations of the `Drop` trait which never calls the function `tproxy_remove` that reads the file. Instead, the `_tproxy_remove` function is called on `self`.

**Comment by blechschmidt** [comment]
> So I haven't made up my mind whether to remove this temporary file.

I can think of three options:
1. We keep the functionality with ownership checks. E.g. the owner UID returned by `fstat` matches `getuid()`.
2. We implement a watcher process. Through a mechanism like a pipe, tun2proxy signals successful termination to the watcher process. If tun2proxy terminates without having written to the pipe, the watcher takes care of cleaning up.
3. We remove the functionality.

As I already said, I am in favor of removing the file. PR #12 addresses this. By using the `Drop` trait implementation, most Rust panics should not lead to failure, cf. https://doc.rust-lang.org/std/ops/trait.Drop.html#panics.

**Comment by ssrlive** [comment]
Version V6.0.0 has solved this issue.

**Comment by blechschmidt** [comment]
To summarize, since @ssrlive is in need of this feature, we agreed on implementing an additional `unsafe-state-file` feature, which is not enabled by default and in particular is not to be used in any production code.
