### ISSUE TITLE
Bypass other IPs instead --bypass args

### ISSUE THREAD

**Issue by shiroedev2024** [tun2proxy/tproxy-config#6]
Check https://github.com/shiroedev2024/leaf/issues/8 and https://github.com/shiroedev2024/leaf/issues/9.

The title is not very clean, imagine I used xray-core and tun2proxy and I used `--bypass` argument to bypass my vmess proxy server. then tun2proxy captures all traffic from my system to the xray-core proxy. then I want to bypass for example China IP CIDR so I added the needed rules in the xray-core config. but not working because tun2proxy captures all traffic. my idea is to use rules and binding IP to the default interface (UNIX) or IP. Also if tun2proxy running and I change my internet interface my connection fails, because need I need to write bypass routes again via the new interface.

A very good example of this is https://github.com/SagerNet/sing-tun.

**Comment by shiroedev2024** [comment]
also, I writing this simple script to test it and it works. I used socket binding in the proxy tool (leaf).
```bash
configure_routing() {
    # add default routes
    ip route add default dev $TUN_NAME table 2022
    ip -6 route add default dev $TUN_NAME table 2022

    # IPv4 rules
    ip rule add from all to 198.18.1.0/24 lookup 2022 pref 9000
    ip rule add from all ipproto icmp goto 9010 pref 9001
    ip rule add not from all dport 53 lookup main suppress_prefixlength 0 pref 9002
    ip rule add not from all iif lo lookup 2022 pref 9002
    ip rule add from 0.0.0.0 iif lo lookup 2022 pref 9002
    ip rule add from 198.18.1.0/24 iif lo lookup 2022 pref 9002
    ip rule add from all nop pref 9010

    # IPv6 rules
    ip -6 rule add from all ipproto ipv6-icmp goto 9010 pref 9000
    ip -6 rule add not from all dport 53 lookup main suppress_prefixlength 0 pref 9001
    ip -6 rule add from all lookup 2022 pref 9001
    ip -6 rule add from all nop pref 9010

    echo "routing configured."
}

revert_routing() {
    # IPv4 Rules
    ip rule del from all to 198.18.1.0/24 lookup 2022 pref 9000
    ip rule del from all ipproto icmp goto 9010 pref 9001
    ip rule del not from all dport 53 lookup main suppress_prefixlength 0 pref 9002
    ip rule del not from all iif lo lookup 2022 pref 9002
    ip rule del from 0.0.0.0 iif lo lookup 2022 pref 9002
    ip rule del from 198.18.1.0/24 iif lo lookup 2022 pref 9002
    ip rule del from all nop pref 9010

    # IPv6 Rules
    ip -6 rule del from all ipproto ipv6-icmp goto 9010 pref 9000
    ip -6 rule del not from all dport 53 lookup main suppress_prefixlength 0 pref 9001
    ip -6 rule del from all lookup 2022 pref 9001
    ip -6 rule del from all nop pref 9010

    echo "routing reverted."
}
```

**Comment by ssrlive** [comment]
To achieve this goal, it may be necessary to open a dedicated thread to handle various bypass CIDRs that are added or deleted at any time, which will greatly increase the complexity of this library. There is no clear plan yet.
PRs are welcome.

**Comment by ssrlive** [comment]
To alleviate this problem, I submitted a PR #7 that changes the value of the bypass parameter from IpAddr to CIDR.

**Comment by shiroedev2024** [comment]
Thanks @ssrlive. currently, making a monitor for listening to default interface changes and rerouting is enough. I will make this for Linux first and test it.
